[builder]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311", "libGL", "libGLU", "glib"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.start]
cmd = "python bot.py"

[variables]
BOT_TOKEN = ""

[healthcheck]
path = "/"
port = 8080
